const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');

class GeminiAutomator {
  constructor() {
    this.userDataDir = path.join(__dirname, 'user_data');
    this.context = null;
    this.page = null;
  }

  async init(customGemUrl) {
    if (!fs.existsSync(this.userDataDir)) {
      throw new Error(`User data directory not found at ${this.userDataDir}. Please run 'node login.js' first to authenticate.`);
    }

    console.log('Launching browser with persistent context...');
    this.context = await chromium.launchPersistentContext(this.userDataDir, {
      headless: false, // For testing, keep it visible. We can set it to true later if we want a fully headless backend.
      viewport: null
    });

    this.page = this.context.pages()[0] || await this.context.newPage();

    console.log(`Navigating to Custom Gem: ${customGemUrl}`);
    await this.page.goto(customGemUrl, { waitUntil: 'domcontentloaded' });

    // Wait for the prompt input box to be visible
    try {
      await this.page.waitForSelector('div[contenteditable="true"]', { timeout: 15000 });
      console.log('Gemini interface loaded and ready.');
    } catch (error) {
      console.error('Failed to find the input box. You might need to authenticate or check the Custom Gem URL.', error);
      throw error;
    }
  }

  async sendPrompt(promptText) {
    if (!this.page) {
      throw new Error('Browser is not initialized. Call init() first.');
    }

    console.log(`Sending prompt: ${promptText.substring(0, 50)}...`);

    // Ensure the input box is ready
    const inputBoxSelector = 'div[contenteditable="true"]';
    await this.page.waitForSelector(inputBoxSelector, { state: 'visible' });

    // Get the current number of responses (so we know which one is the new one)
    const responseContainersSelector = 'message-content'; // General selector for message bubbles
    const previousResponsesCount = await this.page.locator(responseContainersSelector).count();

    // Type the prompt into the input box
    // Use evaluate to set textcontent directly if type doesn't work, but type is safer for React/Angular bindings
    await this.page.fill(inputBoxSelector, promptText);

    // Give it a tiny moment to register the input
    await this.page.waitForTimeout(500);

    // Press Enter to submit
    await this.page.press(inputBoxSelector, 'Enter');

    // In case Enter didn't work, try clicking the send button if visible
    try {
      const sendButtonSelector = 'button[aria-label*="Send"]';
      if (await this.page.locator(sendButtonSelector).isVisible()) {
          await this.page.click(sendButtonSelector);
      }
    } catch(e) {
      // Ignore if button is not found or unclickable, Enter might have worked
    }


    console.log('Waiting for AI to finish generating response...');

    // Wait for a new response container to appear
    await this.page.waitForFunction(
      ({ selector, count }) => document.querySelectorAll(selector).length > count,
      { selector: responseContainersSelector, count: previousResponsesCount },
      { timeout: 120000 } // Wait up to 2 minutes for the initial response to start
    );

    // Now wait for the "generating" indicator to disappear or for the response text to stop changing
    // Gemini usually disables the submit button while generating
    try {
      const submitButtonSelector = 'button[aria-label*="Send"]';
      // Wait for it to become disabled (generating)
      await this.page.waitForSelector(`${submitButtonSelector}[disabled]`, { timeout: 10000 }).catch(() => {});
      // Wait for it to become enabled again (done generating)
      await this.page.waitForSelector(`${submitButtonSelector}:not([disabled])`, { timeout: 300000 }); // Wait up to 5 mins for long generation
    } catch (e) {
       console.log("Could not reliable detect generation state via button, falling back to static wait/network idle");
       await this.page.waitForTimeout(10000); // Fallback wait
    }

    // Extract the text of the *latest* response
    const responses = this.page.locator(responseContainersSelector);
    const newResponseCount = await responses.count();

    if (newResponseCount === previousResponsesCount) {
        throw new Error('No new response was generated by Gemini.');
    }

    // Get the inner HTML of the last response
    const lastResponse = responses.nth(newResponseCount - 1);

    // Sometimes the text isn't fully rendered immediately after the button is enabled
    await this.page.waitForTimeout(2000);

    const htmlContent = await lastResponse.innerHTML();
    const textContent = await lastResponse.innerText();

    console.log('Response generated successfully.');

    return {
      html: htmlContent,
      text: textContent
    };
  }

  async close() {
    if (this.context) {
      console.log('Closing browser...');
      await this.context.close();
      this.context = null;
      this.page = null;
    }
  }
}

module.exports = GeminiAutomator;
